[package]
name = "biblio_json"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.2"
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
toml = "0.9.2"
