[package]
name = "md-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
either = { version = "1.15.0", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
